### ISSUE TITLE
Merge #53 #52 #51 확인사항

### ISSUE THREAD

**Issue by 9oj0e** [9oj0e/project-job-plan#54]
https://github.com/9oj0e/project-job-plan/commit/f90cd9aaf98c0a9d11902db9424d5f1b9307ab56#commitcomment-139563290

# 해결 과제
* 제안 버튼
* 채용 공고 지원시 지원 버튼 사라지게 (`/board/detail`)
* 기업의 구독리스트 view에 채울 내용 더 넣기. (지역, 성별, 나이(년생)
* 구독 사이트 페이지네이션 (`/user/subscription`, `/employer/subscription`)
* DB dummydata 수정

## 이하.. 추가로 발견되는 사항 아래에 comment

**Comment by zeeq123** [comment]
개인회원이 자신의 이력서를 들어가도 구독 버튼이 생김

**Comment by zeeq123** [comment]
평점이 소수점 10자리 이상으로 나옴(기업, 개인 전부)

**Comment by zeeq123** [comment]
채용공고 리스트가 2개가 나옴

**Comment by 9oj0e** [comment]
user/profile
employer/profile
평점 확인 불가

**Comment by yunchocopie** [comment]
기업 회원가입 후 로그인 했을 때 기본 프로필 사진이 안 뜸

**Comment by yunchocopie** [comment]
## 평점
- 개인 -> 기업
  여러 개인 회원이 한 기업에 점수를 매기는거까지는 OK 
  문제 : 이 평점을 기업에서 확인할 때는 4.5로 고정 돼있음

- 기업 -> 개인
  마찬가지

**Comment by 9oj0e** [comment]
# skill
스킬 미 입력시 터짐
### 이력서 추가/수정
* `resume/uploadForm`
* `resume/updateForm`
### 공고 추가/수정
* `board/uploadForm`
* `board/updateForm`
